### ISSUE TITLE
%{recipient.ticket_link} is not working in predefined answers

### ISSUE THREAD

**Issue by markus4000** [osTicket/osTicket-1.8#1459]
Version 1.94 stable

**Comment by markus4000** [comment]
thanx.

**Comment by adrianoprospero** [comment]
For me it still doesn't work even after posting the reply...

**Comment by greezybacon** [comment]
@adrianoprospero is that for alerts to the administrator email address?

**Comment by adrianoprospero** [comment]
No, it's for answering the end user.
Em 27/08/2015 17:05, "Jared Hancock" <notifications@github.com> escreveu:

**Comment by greezybacon** [comment]
I dunno. I'll need a lot more information to setup a test case to replicate your issue. Something more than "it still doesn't work"

**Comment by adrianoprospero** [comment]
The first part of the case is exactly the same as Markus's, but when posting the reply I got this on the e-mail (attatched).
![selecao_065](https://cloud.githubusercontent.com/assets/8454254/9551594/884255d2-4d88-11e5-9018-675ffd33f8c6.png)
![selecao_066](https://cloud.githubusercontent.com/assets/8454254/9551595/884409cc-4d88-11e5-835f-f5e0a49b69ef.png)

**Comment by adrianoprospero** [comment]
What more information would you need?

**Comment by InToSSH** [comment]
Hello,
I still have exactly the same problem, this variable is not replaced by the actual link when sent as a Post reply on a ticket to the end user. All the others work, just not this one. But when I send this reply, there is a gray text footer in the mail, telling the end user to log in and there is the link working properly, it just seems that this variable doesn't get replaced in the reply body (also when the email is delivered just the variable name is shown, instead of the link, exactly as @adrianogoncalves stated)
