### ISSUE TITLE
Advnanced search does not work. 

### ISSUE THREAD

**Issue by erikbaz** [osTicket/osTicket-1.8#1573]
when I select unassigned in the assigned to field in the advanced search I am getting results with assigned tickets.

http://www.screencast.com/t/lVye704p
returns the universe of tickets.

osTicket Version 	v1.9.4 (c18eac4)
Web Server Software 	lighttpd/1.4.28
MySQL Version 	5.5.38
PHP Version 	5.3.10-1ubuntu3.14

**Comment by TraceElements** [comment]
I'm still having this problem in v1.9.5.1 (was hoping the upgrade would fix it) - both the 'Unassigned' option in advanced search and the  'Exclude assigned tickets from open queue' option on the Admin Panel -> Settings -> Tickets menu seem to have no effect.

**Comment by TraceElements** [comment]
( I did notice that this item was marked as a duplicate, however #901 seems more related to Advanced search as a whole.  Since the Admin Panel -> Settings -> Tickets menu option to filter on unassigned doesn't work either, there seems to be some kind of issue with how the 'Unassigned' state is being filtered.  This is why I chose this ticket to comment on.)

**Comment by greezybacon** [comment]
Can anyone verify if the patch in #1857 addresses the issue?
