### ISSUE TITLE
Create new ticket if reply from app mail smartphone

### ISSUE THREAD

**Issue by juraganerka** [osTicket/osTicket-1.8#1916]
why every time when i reply email from system always make a new ticket without subject?
i reply email from my app mail based on android cellphone.

**Comment by ntozier** [comment]
There is really no way for us to assist you with this with out more information.
Version of osTicket?
Version of Android?
Email client that you are using?

I just tried this on my android phone and it worked as I would expect it to.  It updated the ticket with my email.   I am running the default Android email client in 4.4.4, and osTicket 1.9.5.

**Comment by juraganerka** [comment]
@ntozier sorry for incomplete information.
I used osTicket v1.8.0.2 and my smartphone used android v 4.4.
My account email is from gmail,but gmail app but email app from my smartphone.
If i used gmail apps everything is fine.I'ts problem when i reply from smartphone email app.
Strangely,this will be happen if used Samsung smartphone.
I tried many brand like ASUS,LG,SONY,IPHONE then seems nothing trouble.
looks weird,but it's really happen.

**Comment by greezybacon** [comment]
@juraganerka so are you saying this should be an upstream bug report to the Samsung Android email app?

**Comment by juraganerka** [comment]
@ntozier well i don't know.
did you have found any problem like this before?
Are you absolutely sure that this problem not from OS ticket?

**Comment by greezybacon** [comment]
@juraganerka lemme get this straight. Out of six (6) email apps, one is not working properly. And I need to confirm that it's an osTicket related issue?

**Comment by juraganerka** [comment]
@greezybacon i don't know if this issue from osTicket or email apps.
i mean have you ever find this issue before?

**Comment by greezybacon** [comment]
@juraganerka we receive about 5 claims a week that email in osTicket is broken. We make our best effort to ensure that osTicket will work properly with every other mail server and mail client on the planet; however, the fact is is that there are several mail softwares in existence that don't play by the proper rules. Hopefully one day we will convince the world that our mail system works well, but unfortunately for now, the world always assumes that it is osTicket that is broken.

Personally, I believe your issue is with your Samsung smart phone app, considering that you have confirmed that five (5) other smart phone apps work correctly. I would need a lot more information to confirm a problem with osTicket.

Perhaps you could send the raw version of a such email sent by your smart phone, or send the `headers` field from your `ost_ticket_email_info` table for the newly created ticket which was supposed to be threaded.

My hunch is that your phone app is not adding a `References` and `In-Reply-To` header to the email which is supposed to cite the original `Message-ID` header in the email sent to the phone. You could remedy this deficiency by adding `#%{ticket.number}` in the subject line of your new ticket autoresponse and ticket reply templates in Admin Panel -> Emails -> Template -> [Select a template group] -> New ticket autorespose and change the subject line.

**Comment by ntozier** [comment]
Also osTicket v1.8.0.2 is really old and you should upgrade.
