### ISSUE TITLE
1.9.9-1: Closed tickets that are replied to by email aren't reopened. 

### ISSUE THREAD

**Issue by cberescu** [osTicket/osTicket-1.8#2225]
On class.ticket.php shouldn't it be on line 1183 instead of   
```php
if ($autorespond && $this->isClosed() && $this->isReopenable())  
```
this 
```php
if (!$autorespond && $this->isClosed() && $this->isReopenable())
```

**Comment by ntozier** [comment]
The line that you mention hasn't changed in quite some time and multiple versions.
So I doubt it.  Have you disabled re-opening of tickets?

Please go to Admin panel -> Manage -> Lists -> Ticket Statuses.
Click on Items tab.
Click on Closed.
Click on Item Properties tab
Do you have "Allow Reopen:" checked?

**Comment by cberescu** [comment]
yes, already checked that.

**Comment by mckaygerhard** [comment]
i try to clarify on this, in part, @cberescu have right in part ...

If I turn off answered reopen by post, fine.
But when it is turned off, the system does not accept open tickets through the mail.

**Comment by dannydulai** [comment]
I'm 100% sure the bug is the original issue. I put some trace in the code, and $autorespond is empty.

It doesn't even make sense the way it is now -- why would you reopen ONLY if the message was an autorespond message?

I changed my code to be `!$autorespond` and all is working :-)

**Comment by t-oster** [comment]
...may explain my issue #2564

**Comment by t-oster** [comment]
the variable name $autorespond is misleading. The only call to that function is in the postMessage function and looks like
````
$this->onMessage($message, $alerts); 
````
so if the parameter is TRUE, it should notify the user and reopen the ticket, otherwise not. The name $autorespond can be understood as "isAutorespond" like in isBounceOrAutoReply and thus would have the inverse meaning. But like it is called right now, 
````
if ($autorespond && $this->isClosed() && $this->isReopenable()) 
````
is the correct interpretation.

But as described in #2564 some mails get classified as **isBounceOrAutoReply** and thus lead to your error.

**Comment by cberescu** [comment]
Yes, that is true @t-oster, the line is correct. Closing this.
