### ISSUE TITLE
  Feature request: customize "Post Internal Note"

### ISSUE THREAD

**Issue by JanKraljic** [osTicket/osTicket-1.8#2262]
I didn't find any option that i can customize "Post Internal Note".  Is there any?

The best option would be something like template forms to chose like: Simple note, Work report, Links, ..., 

Actually am looking something like "Work report" internal note where we can fill up some *time that was used* for resolving ticket. That would help us since sometimes client support is payable or we just want to know how much time was used for internal tracking.

**Comment by infectormp** [comment]
@JanKraljic are you try use Canned response?

**Comment by JanKraljic** [comment]
Internal does not have option of "Canned reponse". At the moment we are solving that with "fixed" pre-agreed "title" of internal note.

**Comment by ntozier** [comment]
Q: I didn't find any option that i can customize "Post Internal Note". Is there any?
A: No, Internal Notes do not have canned responses.  But then since internal notes are literally just that, I'm not real sure why you would need canned responses for them.  They are really designed to be quick and dirty notes to anyone reading the thread.

**Comment by JanKraljic** [comment]
all I need is to write time that was used for ticket to solve, that can we charged our client for that.

**Comment by ntozier** [comment]
I think i'm confused then... why would you need canned responses to post a number?

**Comment by infectormp** [comment]
@JanKraljic you can try install mod https://github.com/osTicket/osTicket-1.8/pull/1419 for time tracking

**Comment by JanKraljic** [comment]
Looks just what I need. Thx!
