### ISSUE TITLE
v 1.10 RC1 ... passthrough disabeld no customer login - CSRF Error

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket-1.8#2349]
I just tried a different problem to reproduce.
In addition I have HTTP passthrough disabled, because I wanted to Login with another customer account. but not the left, I got mistakes over the CSRF.

![unbenannt](https://cloud.githubusercontent.com/assets/13413719/9018269/9260e8f0-37dd-11e5-9c98-e855d9b3472a.PNG)

without http passthrough there is no more customer can Login,
Login as the agent continues to work normally.

I've activated http again , the login over passthrough works, 
the Login with a Localen OST account dosen´t work

can confirm that someone

system:
Server 2012r2
IIS 8.5
MySQL 5.7
PHP 5.4
Modul: LDAP an HTTP passthrough

**Comment by greezybacon** [comment]
I think this was fixed in 54b8a8ce4e0934e491cb53d6e22fd0a53322d8d0

**Comment by oneilak** [comment]
ok it works :-)

**Comment by greezybacon** [comment]
Please reopen if the problem persistes

**Comment by diegokangry** [comment]
i have problem with error
while log in  error Valid CSRF Token Required

**Comment by ntozier** [comment]
If you are running 1.10rc1 then, you should upgrade to the current beta if you are going to run beta software.

**Comment by Apante** [comment]
Hello , I have a problem  , I am new with php  and MySQL  . I am trying to install osTicket but I get  prompted with Valid CSRF Token Required. I tried searching for answered but  nothing  solved my problem . If someone can help me please do :D .

**Comment by ntozier** [comment]
I invite you to post your system environment and configuration details at the forums with a description of the problem.  http://osticket.com/forum

**Comment by bstetler** [comment]
I get this error everytime I login to the admin panel but if I removed login.php from url it works..

**Comment by BlackTiger63** [comment]
Got the same issue here on 1.10 after disabling https on my site I tried to login via http and got the login screen.
After loggin in the message Valid CSRF Token Required appeared.
If I remove login.php from the url I get the login screen again.

**Comment by bstetler** [comment]
Ya I have had that experience as well. If i try a few times I eventually get in. I dont know if it is the shared environment that the site is hosted on our what. I have seen the psts about signing up for the forum but honestly I do not want to sign up for another forum.
osTicket (v1.10) 
 php -v
PHP 5.4.16 (cli) (built: Nov  6 2016 00:29:02)
Copyright (c) 1997-2013 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2013 Zend Technologies
with Zend OPcache v7.0.5, Copyright (c) 1999-2015, by Zend Technologies
httpd -v
Server version: Apache/2.4.25 (CentOS)

mysql -V
mysql  Ver 15.1 Distrib 5.5.52-MariaDB, for Linux (x86_64) using readline 5.1

Server version: 5.5.52-MariaDB MariaDB Server

**Comment by Sagar-AppLogics** [comment]
Exact Same issue as described above

Microsoft Azure - Web Application
PHP 7.1
MySQL 5.1

**Comment by Sagar-AppLogics** [comment]
Guys i resolved my issue experienced with my azure based system by going down to PHP 5.6
I compared to other setups i have in local development environments and that was the only discrepancy. Supposedly supports 5.3+ but i guess (unless its an issue on the azure php 7.1 config) that doesn't include php 7.1.

Would be nice to get to the bottom of this non the less.

**Comment by BlackTiger63** [comment]
Nice that this helped for you, but I was running PHP 5.6 already and also have the issue. So going down to PHP 5.6 will not solve it for everybody.

**Comment by Synt4xError** [comment]
Please open a thread on the forums for support. Since it works for some and not others I'd assume its local environment related and not and OST bug.
http://osticket.com/forum/




Sincerely, 
Rutger Penick

**Comment by BlackTiger63** [comment]
LoL, I only seen 1 comment that it works. But never mind I'm working with https anyway now.

**Comment by Sagar-AppLogics** [comment]
@BlackTiger63 you make a good point, i went ahead after and ran into some additional issues and turned out that Azures MySQL instance was causing a problem somehow/somewhere and because it wasn't a dedicated instance the admin privileges were almost non existent. It could be that a relevant permission over the schema was missing but who knows. However I did setup a dedicated instance and also compared to a local network instance and carried on testing and only got this error when connecting the a PHP 7.1 instance. Using PHP 7.0 was ok. Might be worth seeing if going up to PHP 7.0 could solve your issue? What is strange though, you mention it works with https but for me, but it had no effect on any of the tested configs.

**Comment by BlackTiger63** [comment]
Unfortunately I can't just upgrade to PHP 7.0 because I'm running a shared hosting server with a customers not heaving all applications ready yet for PHP 7.0.
I did not change any php configs, only installed a LetsEncrypt certificate, change the site and Osticket to https and the error was instantly gone.
mysql  Ver 14.14 Distrib 5.5.53, for Linux (x86_64) using readline 5.1
PHP 5.6.30 (cli) (built: Mar  9 2017 21:54:40)
Apache/2.4.25 (Unix)
It might be that the upgrade from php 5.6.29 to 5.6.30 fixed things.

However, I could do a test on a private account on the server without https, to see if the issue occurs again if somebody's interested.
