### ISSUE TITLE
v1.9.9-1 - Advance Search for large query returns all results

### ISSUE THREAD

**Issue by holodoctor1** [osTicket/osTicket-1.8#2381]
Doing an advanced search appears to find all the tickets related to the search, but when the search is large (around over 1,000 tickets) the system works for about 10 seconds after pressing view, then returns all tickets in the system (i.e. throws out the search).

How can I make the system return the correct results?

![osticket____staff_control_panel1](https://cloud.githubusercontent.com/assets/13681611/9117357/c4d0fef4-3c26-11e5-81fa-9c0541adeccd.jpg)
![osticket____staff_control_panel2](https://cloud.githubusercontent.com/assets/13681611/9117361/c9518818-3c26-11e5-99e4-72857e997ce8.jpg)

**Comment by harrisyn** [comment]
Experienced the same issue and I understand its probably resolved in 1.10 however I dont have that much data in my test platform.
This issue is easily reproduced by searching for data between two months or when the query returns a large amount of ticket ids. the ticket id are kept in SESSION and I believe it isnt able to hold past a certain amount of data.

I was only able to resolve mine (albeit in a dirty hack) by writing the ticket ids to a file and reading it back in the tickets page. This has worked for me without problems.

**Comment by holodoctor1** [comment]
Harrisyn - that would appear to resolve our issue as well in 1.9.9.  I'm a bit new to github - what changes did you make to fix this?  Thank you.

**Comment by greezybacon** [comment]
This is addressed in the v1.10 releases. Advanced search was rewritten to overcome these limitations

**Comment by simonebracaloni** [comment]
As workaround in previous versions, without touching the code, you can change the type of session_data, in the ost_session table in your db, from BLOB to a bigger type (eg. MEDIUMBLOB or LONGBLOB)

**Comment by holodoctor1** [comment]
Simonebracaloni - thank you very much - it looks like this does indeed fix this issue in the current version.
