### ISSUE TITLE
v1.9.11 - German Special Version - DB Fehler

### ISSUE THREAD

**Issue by oneilak** [osTicket/osTicket-1.8#2631]
hey guys,

there is a "Germanized" slightly modified version of OS tickets.
while writing an internal memo comes sporadically db error.
somebody has an idea on this?

DB Error #1146
[SELECT a.ticket_id, concat(a.number,":",b.subject) as label FROM `ost_ticket` as a LEFT JOIN ost_ticket__cdataas b on a.ticket_id = b.ticket_id LEFT JOIN ost_user_email as c on (a.user_id =c.user_id) WHERE c.address=(SELECT ab.address FROM ost_ticket AS aa LEFT JOINost_user_email AS ab ON ( aa.user_id = ab.user_id ) WHERE aa.ticket_id =373)and a.status_id = 1 and a.ticket_id<> 373 ORDER BY `created` DESC ]

Table 'd01cdfb9.ost_ticket__cdata' doesn't exist<br/> <br />
---- Ablaufverfolgung ----<br />
#0 (root)/include/mysqli.php(177):osTicket->logDBError('DB Error #1146', '[SELECT a.ticke...')<br />
#1(root)/include/staff/ticket-view.inc-mergeForm.php(26): db_query('SELECTa.ticket...')<br />
#2 (root)/include/staff/ticket-view.inc.php(746): include('/www/htdocs/w01...')<br/>
#3 (root)/scp/tickets.php(515):require_once('/www/htdocs/w01...')<br />
#4 {main}

**Comment by Chefkeks** [comment]
> there is a "Germanized" slightly modified version of OS tickets.

What do you mean with that?

Asking since there is a webpage osticket.com<b>.de</b> and they provide a forked/modified version of osTicket with German Language that is NOT related and NOT supported here or on the forum.

Only the official version from <b>osticket.com</b> is supported and the language packs from osticket.com / i18n.osticket.com.

Knowing that really well since I'm one of the translators and proofreaders of the german language pack and also forum moderator and it's not the first time folks are seeking for help of the un-supported special german osTicket fork/mod.

Cheers,
Michael

**Comment by oneilak** [comment]
hey michael
I am aware that it will not be supported here :-)
I just thought to ask if anyone has ne spontaneous idea costs nothing :-)

**Comment by Chefkeks** [comment]
OK, I understand.

So after a little search in the forum, I found this discussion, which maybe helps:
http://osticket.com/forum/discussion/85258/db-error-1146

BUT PLEASE: Make a backup before you try something ;)

**Comment by oneilak** [comment]
thx michael :-)
