### ISSUE TITLE
Latest build August, long time ago. [Question]

### ISSUE THREAD

**Issue by gitfve** [osTicket/osTicket-1.8#2849]
There are many outstanding, for me the editor problem can't go on (https://github.com/osTicket/osTicket-1.8/issues/2373#issuecomment-158281181). 
Latest build August, long time ago.

**Comment by mfelber** [comment]
I don't see a question..

**Comment by gitfve** [comment]
My question was missing, ok here it is: When to expect a working solution for the editor problem(as #2373)?

**Comment by mfelber** [comment]
Wouldn't it be better to ask this question in the issue report you have mentioned in order to avoid multiple issue reports for the same issue (it is a duplicate issue)...

The last reaction from one of developers to this was that this will be solved in osTicket 1.10 due to an upgrade of the used html editor (redactor from imperavi) like you can see in https://github.com/osTicket/osTicket-1.8/issues/2373#issuecomment-133041578 . 

My experience is that exact release dates will not be communicated. I'm just a normal user so I can't tell you really more about this..

**Comment by gitfve** [comment]
I agree, will move it.
