### ISSUE TITLE
Loosing Fileupload

### ISSUE THREAD

**Issue by markus4000** [osTicket/osTicket-1.8#695]
When a client leaves a requiered field empty, chooses some files and subits the form, the system responds with the message "field required"... thats good so far. but unfortunately the system looses the choosen files. Is there a Mod for that, to keep the files selected, even if a required field was empty?

**Comment by markus4000** [comment]
I tried it with 1.9.6 and it still doesn't work.
can you check?

**Comment by greezybacon** [comment]
@markus4000 I disagree. We have drag and drop file support for files in v1.9.6, which are definitely preserves the files uploaded thus far when validation errors occur elsewhere in the form.

**Comment by Hannibal226** [comment]
@greezybacon 
Is this a completly different section or is Upload in Knowledgebase the same procedure?

Because I can confirm this Bug in 1.9.7 in Knowledgebase.
When u create a FAQ with Files attached and save the new FAQ, the attachement get lost.
Next edit and adding will attach the file.

CHEERS

**Comment by greezybacon** [comment]
@Hannibal226 is there a reason you haven't tried a later version of v1.9?

**Comment by Hannibal226** [comment]
@greezybacon
Hmm I wanted but first I hadn't time to test and later I saw already the RC
versions.
So I decided to wait for the 1.10 build as it also have the most important
missing things like flexibel column on ticket view and develop-next
improvements.
U mean it doesn't make sense waiting for it or there is a few in end of
coding for u? xD
(sorry I know no ETAs, but it's really general asked)

But u said it should be fixed on 1.9.6 so that's why I thought I mentioned
this.

CHEERS

Jared Hancock <notifications@github.com> schrieb am Mi., 30. Sep. 2015
20:12:

**Comment by greezybacon** [comment]
I know there have been troubles with attachments on the FAQ and Canned Response pages. I think it might be worthwhile upgrading to v1.9.12 (which doesn't require a database migration) and resting your issue. v1.10 should be released as stable soon, but as you said, there are not ETAs

**Comment by Hannibal226** [comment]
Alright, so I'll test the upgrade tomorrow, hoping nothing will brake,
otherwise I can live with this until 1.10 is there.

At this point thanks again for all ur work and biggest respect. I'll be
stay tuned.

CHEERS!

Jared Hancock <notifications@github.com> schrieb am Mi., 30. Sep. 2015
20:23:

**Comment by Hannibal226** [comment]
@greezybacon 
Just to let u know:
I updated today to 1.9.12 without problems (thanks), BUT
still the problem that adding a new FAQ with file won't show them on 'save'.

So I din't know if I should open a new issue or u definitly know it's fixed in 1.10,
so just let me know then, what to do here.

CHEERS!

**Comment by greezybacon** [comment]
@Hannibal226 thanks for tracking that down. Judging by the conversation at the top of this thread, I think that constitutes a separate issue

**Comment by Hannibal226** [comment]
@greezybacon 

Alright, so I create a new issue then.

CHEERS

https://github.com/osTicket/osTicket-1.8/issues/2606
